<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite ignored="0" hostname="DESKTOP-P6GQ53L" failures="1" tests="4" name="Test" time="9.176" errors="0" timestamp="2023-12-03T21:18:33 IST">
  <testcase classname="api.test.testValidations" name="testPOSTBook" time="4.142">
    <failure type="java.lang.AssertionError" message="expected [1873121466] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1873121466] but found [0]
at api.test.testValidations.testPOSTBook(testValidations.java:43)
at java.base/java.util.ArrayList.forEach(ArrayList.java:1511)
... Removed 32 stack frames]]>
    </failure>
  </testcase> <!-- testPOSTBook -->
  <testcase classname="api.test.testValidations" name="testGETBook" time="1.617"/>
  <testcase classname="api.test.testValidations" name="testPUTBook" time="1.62"/>
  <testcase classname="api.test.testValidations" name="testDELETEBook" time="1.475"/>
</testsuite> <!-- Test -->
